version: '3'
services:
    admin:
        build:
            context: .
            dockerfile: video-Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - admin_db
    admin_db:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
          - 33063:3306
